name: "Textile Bucket - Deploy"
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  bucket_push:
    runs-on: ubuntu-latest
    name: Push Textile Bucket
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: push action
      id: push
      uses: textileio/github-action-buckets@v18
      with:
        key: ${{ secrets.TEXTILE_ACCOUNT_KEY }}
        secret: ${{ secrets.TEXTILE_ACCOUNT_SECRET }}
        bucket: "libertas"
        thread: "bafkznmnsix6r3jwe6ntk6ci57kbrzeuks4kwnsm4y42y5r6vh67zhay"
        path: "."
    - run: echo "bucket - ${{ steps.push.outputs.key  }}"
    - run: echo "ipfs - ${{ steps.push.outputs.ipfs }}"
    - run: echo "ipfs link - ${{ steps.push.outputs.ipfsUrl }}"
    - run: echo "ipns - ${{ steps.push.outputs.ipns }}"
    - run: echo "ipns link - ${{ steps.push.outputs.ipnsUrl }}"
    - run: echo "hub - ${{ steps.push.outputs.hub }}"
    - run: echo "www - ${{ steps.push.outputs.www }}"
    - name: Bucket Replication
      id: replicate
      uses: textileio/github-action-bucket-replicate@v1
      with:
        cid: ${{ steps.push.outputs.ipfs }}
        bucket: 'libertas'
        pinata_key: ${{ secrets.PINATA_KEY }}
        pinata_secret: ${{ secrets.PINATA_SECRET }}
        pinata_name: 'libertas'
